### ISSUE TITLE
Problem with unconditioned generation

### ISSUE THREAD

**Issue by trltzy** [lzzcd001/MeshDiffusion#21]
**Describe**
Runing Unconditional Generation on ubuntu. Finished first step successfully, and show the error below in second step. Seems like somthing wrong with the ninjia, can you help me?

**Reproduce**

> python eval.py --config configs/res64.json -o outdir -sp '../outputs/0.npy' -ds 3.0 --angle-ind 25 -ns 1

**Error**

> Warning:
Unable to load the following plugins:

        libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/usr/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

Traceback (most recent call last):
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/code/MeshDiffusion/nvdiffrec/eval.py", line 367, in <module>
    glctx = dr.RasterizeGLContext()
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/6] c++ -MMD -MF common.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/common.cpp -o common.o 
[2/6] c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
FAILED: rasterize_gl.o 
c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
In file included from /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/rasterize_gl.h:16,
                 from /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/rasterize_gl.cpp:9:
/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/6] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/glutil.cpp:14:
/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[4/6] c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
FAILED: torch_rasterize_gl.o 
c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
In file included from /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/../common/rasterize_gl.h:16,
                 from /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp:12:
/root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/../common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[5/6] c++ -MMD -MF torch_bindings_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/TH -isystem /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/miniconda3/envs/meshdiffusion/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /root/miniconda3/envs/meshdiffusion/lib/python3.9/site-packages/nvdiffrast/torch/torch_bindings_gl.cpp -o torch_bindings_gl.o 
ninja: build stopped: subcommand failed.

**Comment by lzzcd001** [comment]
You need EGL in your system. Try `conda install -c conda-forge mesa-libegl-devel-cos6-x86_64 mesa-libgl-devel-cos6-x86_64`, or any implementation of EGL through `sudo apt install` if you have sudo rights.
