### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '../res64/chair/0000' full_id_list = [int(x.rstrip().split('_')[-1][:-len(self.extension)-1]) for i, x in enumerate(self.fpath_list)]

### ISSUE THREAD

**Issue by jpainam** [lzzcd001/MeshDiffusion#29]
Hi. Thank you for releasing the code.
When I run 
`python main_diffusion.py --mode=train --config=./configs/res64.py --config.data.meta_path=./meta_file.json --config.data.filter_meta_path=./metadata/train_split/chair_train.json --config.data.extension=npy` i get the following error:

```python
W0222 02:11:24.233449 140201066399616 utils.py:10] No checkpoint found at PLACEHOLDER/checkpoints-meta/checkpoint.pth. Returned the same state as input
----- Assigning mask -----
I0222 02:11:24.233782 140201066399616 trainer.py:56] ./meta_file.json, ./metadata/train_split/chair_train.json
----- Assigning mask -----
work dir: PLACEHOLDER
sdf normalized or not:  True
dataset  with sdf normalized: True
Traceback (most recent call last):
  File "main_diffusion.py", line 28, in <module>
    app.run(main)
  File "/miniconda3x86/envs/get3d/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "//miniconda3x86/envs/get3d/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "main_diffusion.py", line 21, in main
    trainer.train(FLAGS.config)
  File "/MeshDiffusion/lib/diffusion/trainer.py", line 68, in train
    train_dataset = ShapeNetDMTetDataset(json_path, deform_scale=config.model.deform_scale, aug=True, grid_mask=mask, 
  File "MeshDiffusion/lib/dataset/shapenet_dmtet_dataset.py", line 25, in __init__
    full_id_list = [int(x.rstrip().split('_')[-1][:-len(self.extension)-1]) for i, x in enumerate(self.fpath_list)]
  File "/MeshDiffusion/lib/dataset/shapenet_dmtet_dataset.py", line 25, in <listcomp>
    full_id_list = [int(x.rstrip().split('_')[-1][:-len(self.extension)-1]) for i, x in enumerate(self.fpath_list)]
ValueError: invalid literal for int() with base 10: '../res64/chair/0000'
```
This line throws an error `full_id_list = [int(x.rstrip().split('_')[-1][:-len(self.extension)-1]) for i, x in enumerate(self.fpath_list)]`. 

Why are you trying to `split`

```bash

meta_file.json
{
"../res64/chair/0000.npy"
"../res64/chair/0001.npy"
...
}

shapenet_json
{
"chair/c97b5b80a24030ae70e99aac955544a0/model.obj"
"chair/fbca73a2c226a86a593a4d04856c4691/model.obj"
"chair/de3e082195346ca419fb4103277a6b93/model.obj"
...
}
```

What am I missing here?

Thank you.

**Comment by lzzcd001** [comment]
Append `.split('/')[-1]` to the back of `x.rstrip().split('_')[-1]`. It is just to extract the IDs in the filenames.
