### ISSUE TITLE
torch/../common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory #include <EGL/egl.h> not

### ISSUE THREAD

**Issue by jpainam** [lzzcd001/MeshDiffusion#30]
Hi. II have this error when running
`python fit_dmtets.py --config ./configs/res64.json --meta-path ../meta_path/shapenet_json/chair.json --out-dir ../dmtet_data_path --index 0 --split-size 100000
` 
I already installed `conda install -c conda-forge mesa-libegl-devel-cos6-x86_64 mesa-libgl-devel-cos6-x86_64` (#21 ) but the error persist.

```python
ulti_gpu False
tet_path ./data/tets/64_tets_cropped.npz
first_stage_deform 2.0
second_stage_deform 3.0
---------
Using dmt grid of resolution 64
Traceback (most recent call last):
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1717, in _run_ninja_build
    subprocess.run(
  File "~/miniconda3x86/envs/mesh/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fit_dmtets.py", line 636, in <module>
    glctx = dr.RasterizeGLContext()
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1449, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/4] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/TH -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem ~/miniconda3x86/envs/mesh/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/TH -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem ~/miniconda3x86/envs/mesh/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp:14:
~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[2/4] c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/TH -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem ~/miniconda3x86/envs/mesh/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
FAILED: rasterize_gl.o 
c++ -MMD -MF rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/TH -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem ~/miniconda3x86/envs/mesh/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.cpp -o rasterize_gl.o 
In file included from ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.h:16,
                 from ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/rasterize_gl.cpp:9:
~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
[3/4] c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/TH -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem ~/miniconda3x86/envs/mesh/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
FAILED: torch_rasterize_gl.o 
c++ -MMD -MF torch_rasterize_gl.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/TH -isystem ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem ~/miniconda3x86/envs/mesh/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp -o torch_rasterize_gl.o 
In file included from ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/../common/rasterize_gl.h:16,
                 from ~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/torch_rasterize_gl.cpp:12:
~/miniconda3x86/envs/mesh/lib/python3.8/site-packages/nvdiffrast/torch/../common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

```

**Comment by jpainam** [comment]
Fixed, In case someone have the same error, 
Replace `glctx = dr.RasterizeGLContext()` in `fit_dmtets.py, line `636`,  by `glctx = dr.RasterizeCudaContext()`

See https://github.com/nv-tlabs/GET3D/issues/50
